config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :admin, only: [:index]

  resources :rates, only: [:index, :update]

  post '/update_rates_data' => 'rates#update_rates_data'
  root 'rates#index'

  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rate.rb
class Rate < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @rates = Rate.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    I18n.locale = 'ru'
  end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  def index
    @rates = Rate.all
  end

  def update
    rate = Rate.find(params[:id])

    old_value = rate.value

    rate.update!(
      value: params[:rate][:forced_value],
      forced_value: params[:rate][:forced_value],
      forced_until: params[:rate][:forced_until],
    )

    BroadcastRate.new(rate).broadcast
    ChangeValueToNormalWorker.perform_at(rate.forced_until, rate.id, old_value)
  end

  def update_rates_data
    UpdateRatesData.update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_page_name
    "#{controller_name}-#{action_name}"
  end
end

app/views/admin/_forced_rate_widget.erb
<%= form_for(rate, html: { class: 'card' }) do |f| %>
  <div class="card-body">
    <div class="text-information">
      <h4 class="card-title"><%= t("currency.#{rate.code}") %></h4>
      <h6 class="card-subtitle"><%= rate.code %></h6>
    </div>
    <div class="container-fluid">
      <div class="row">
        <div class="col-5">
          <%= f.text_field(:forced_value, class: 'form-control', placeholder: 'Курс') %>
        </div>
        <div class="col-7">
          <%=
            f.text_field(
              :forced_until,
              class: 'form-control datetimepicker',
              placeholder: 'До',
            )
          %>
        </div>
      </div>
      <div class="row submit-button">
        <div class="col">
          <%= f.submit(class: 'btn btn-primary btn-lg') %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/index.html.erb
<% content_for(:title) { t("admin.title") } %>

<div class="container-fluid">
  <div class="alert alert-primary">Формат даты: год-месяц-день час:минута:секунда</div>
  <div class="row text-center">
    <% @rates.each do |rate| %>
      <div class="col-md-4 col-lg-3">
        <%= render 'forced_rate_widget', rate: rate %>
      </div>
    <% end %>
  </div>
</div>

app/views/application/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%=
    link_to(
      'Курс валют',
      root_path,
      class: 'navbar-brand',
    )
  %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%=
          link_to(
            'Ручной ввод',
            admin_index_path,
            class: 'nav-link',
          )
        %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%= [content_for(:title), 'Курсы валют'].compact.join(' - ') %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
</head>
<body class="<%= current_page_name %>">
  <div class='top-bar'>
    <%= render 'menu' %>
  </div>
  <%= yield %>
</body>
</html>

app/views/rates/_rate_widget.html.erb
<div class="card rate-card-<%= rate.id %>">
  <div class="card-body">
    <div class="text-information">
      <h4 class="card-title"><%= t("currency.#{rate.code}") %></h4>
      <h6 class="card-subtitle"><%= rate.code %></h6>
    </div>
    <h3 class="rate-value"><%= rate.value %></h3>
  </div>
</div>

app/views/rates/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <%= form_tag(update_rates_data_path, remote: true) do %>
          <%= submit_tag('Обновить данные извне', class: 'btn btn-primary btn-lg') %>
      <% end %>
    </div>
  </div>

  <div class="row text-center">
    <% @rates.each do |rate| %>
      <div class="col-md-4 col-lg-3">
        <%= render 'rate_widget', rate: rate %>
      </div>
    <% end %>
  </div>
</div>